In [1]:
import numpy as np
import NeuralNet

In [2]:
np.random.seed(0)

In [3]:
# Learn to map 3 inputs to 0 all the time
nn1 = NeuralNet.NeuralNet(3, [1], ["linear"])

In [4]:
nn1.layers

[array([[ 1.76405235,  0.40015721,  0.97873798]])]

In [5]:
nn1.biases

[array([[ 1.]])]

In [6]:
nn1.eval(np.array([0., 0., 0.]))

array([[ 1.]])

In [7]:
nn1.eval(np.array([1., 1., 1.]))

array([[ 4.14294754]])

In [8]:
eval1 = np.sum(nn1.layers[0]) + nn1.biases[0]
eval1

array([[ 4.14294754]])

## Evaluation seems to be good

In [9]:
args = nn1.eval_sup(np.array([1., 1., 1.]).reshape(-1, 1), 
                    np.array([0]).reshape(-1, 1))
args

(8.5820071531356241, array([[ 1.],
        [ 1.],
        [ 1.]]), array([[0]]), [array([[ 4.14294754]])])

In [10]:
eval1**2 / 2

array([[ 8.58200715]])

In [11]:
nn1.gradient_backprop(*args[1:])

([array([[ 4.14294754,  4.14294754,  4.14294754]])], [array([[ 4.14294754]])])

In [12]:
args = nn1.eval_sup(np.array([1., 0, 0]).reshape(-1, 1), 
                    np.array([0]).reshape(-1, 1))
args

(3.8199926856246731, array([[ 1.],
        [ 0.],
        [ 0.]]), array([[0]]), [array([[ 2.76405235]])])

In [13]:
eval1**2 / 2

array([[ 8.58200715]])

In [14]:
nn1.gradient_backprop(*args[1:])

([array([[ 2.76405235,  0.        ,  0.        ]])], [array([[ 2.76405235]])])

In [15]:
np.random.seed(111)
training_data = np.random.random((3, 1000)) * 2 - 1
training_data

array([[ 0.22434035, -0.66186049, -0.12788196, ..., -0.57118306,
         0.67756401, -0.79464301],
       [ 0.0410711 ,  0.56544252,  0.61709815, ..., -0.88916184,
        -0.43158538, -0.94396556],
       [ 0.58664042, -0.86502052,  0.79083285, ...,  0.14630958,
         0.73043918, -0.59853204]])

In [16]:
training_out = np.zeros((1, 1000))

In [37]:
for i in range(250):
    nn1.train_step(training_data, training_out, learning_rate=0.01)

In [38]:
nn1.layers

[array([[ 0.00109731,  0.0001849 ,  0.00085903]])]

In [39]:
nn1.biases

[array([[  2.44468947e-06]])]

In [40]:
nn1.eval(np.array([1., 1., 1.]))

array([[ 0.00214369]])

# It seemed to learn this function
# Try a new function (always output 2 0s given 4 inputs)

In [61]:
np.random.seed(444)
nn2 = NeuralNet.NeuralNet(4, [2], ["linear"])

In [62]:
nn2.layers

[array([[ 0.35743992,  0.3775384 ,  1.38233789,  1.17554883],
        [-0.9392757 , -1.14315015, -0.54243951, -0.54870808]])]

In [63]:
nn2.biases

[array([[ 1.],
        [ 1.]])]

In [64]:
np.random.seed(111)
training_data = np.random.random((4, 256)) * 2 - 1
training_data

array([[ 0.22434035, -0.66186049, -0.12788196, ...,  0.87379029,
         0.3475741 ,  0.18885069],
       [-0.3099828 , -0.83286814,  0.15868007, ...,  0.19688836,
        -0.3889808 ,  0.70714174],
       [ 0.49267945, -0.41075351,  0.68135561, ..., -0.64920452,
        -0.60310764,  0.2384976 ],
       [-0.05291177, -0.09005287,  0.68010314, ..., -0.53248495,
        -0.34262201, -0.10168198]])

In [65]:
training_out = np.zeros((2, 256))

In [68]:
for i in range(1001):
    e = nn2.train_step(training_data, training_out, learning_rate=1e-2)
    
    if i % 100 == 0:
        print(f"{i}: {e}")

0: 2.0649263201947026
100: 0.663344226323955
200: 0.2921814500950592
300: 0.14645276495467485
400: 0.07659107676438395
500: 0.04068462825575084
600: 0.021785094960438116
700: 0.011730838660983595
800: 0.006345885636441964
900: 0.0034464027150222514
1000: 0.0018781292598433602


# Same one but with sigmoidal neurons

In [81]:
np.random.seed(444)
nn3 = NeuralNet.NeuralNet(4, [2], ["sigmoid"])

In [82]:
nn3.layers

[array([[ 0.35743992,  0.3775384 ,  1.38233789,  1.17554883],
        [-0.9392757 , -1.14315015, -0.54243951, -0.54870808]])]

In [83]:
nn3.biases

[array([[ 1.],
        [ 1.]])]

In [84]:
np.random.seed(111)
training_data = np.random.random((4, 256)) * 2 - 1
training_data

array([[ 0.22434035, -0.66186049, -0.12788196, ...,  0.87379029,
         0.3475741 ,  0.18885069],
       [-0.3099828 , -0.83286814,  0.15868007, ...,  0.19688836,
        -0.3889808 ,  0.70714174],
       [ 0.49267945, -0.41075351,  0.68135561, ..., -0.64920452,
        -0.60310764,  0.2384976 ],
       [-0.05291177, -0.09005287,  0.68010314, ..., -0.53248495,
        -0.34262201, -0.10168198]])

In [85]:
training_out = np.zeros((2, 256))

In [95]:
for i in range(1001):
    e = nn3.train_step(training_data, training_out, learning_rate=1e-1)
    
    if i % 100 == 0:
        print(f"{i}: {e}")

0: 0.004783232263008053
100: 0.004378525256699687
200: 0.004035579008222993
300: 0.003741450204976392
400: 0.0034865405146258096
500: 0.0032635897347240736
600: 0.0030670097888240533
700: 0.0028924328042213023
800: 0.0027363974460186693
900: 0.0025961267761230667
1000: 0.002469368058211811


In [96]:
nn3.layers

[array([[ 0.10313752,  0.18028451,  0.49307971,  0.42667118],
        [-0.29375287, -0.23006409, -0.10273709, -0.2651007 ]])]

In [97]:
nn3.biases

[array([[-3.06793753],
        [-3.02553073]])]

# Try an ez 2 layers

In [2]:
np.random.seed(6)
nn4 = NeuralNet.NeuralNet(1, [1, 1], ["linear"]*2)

In [3]:
nn4.layers

[array([[-0.31178367]]), array([[ 0.72900392]])]

In [4]:
nn4.biases

[array([[ 1.]]), array([[ 1.]])]

In [5]:
args = nn4.eval_sup(np.array([1.]).reshape(-1, 1), 
                    np.array([0.]).reshape(-1, 1))
args

(1.1275700696435329,
 array([[ 1.]]),
 array([[ 0.]]),
 [array([[ 0.68821633]]), array([[ 1.5017124]])])

In [6]:
(-.3117+1)*.729+1

1.5017707

In [7]:
res = nn4.gradient_backprop(*args[1:])
res

([array([[ 1.09475423]]), array([[ 1.03350299]])],
 [array([[ 1.09475423]]), array([[ 1.5017124]])])

In [8]:
1.5017124 * 0.68821633

1.033502996643492

In [9]:
1.5017124 * 0.72900392

1.094754226312608

In [10]:
np.random.seed(111)
training_data = np.random.random((1, 256)) * 2 - 1
training_out = np.zeros((1, 256))

In [14]:
for i in range(1001):
    e = nn4.train_step(training_data, training_out, learning_rate=5e-2)
    
    if i % 100 == 0:
        print(f"{i}: {e}")

0: 3.5437193048580607e-06
100: 2.862009601332926e-06
200: 2.3120960961139934e-06
300: 1.8682717867967547e-06
400: 1.5099220676623368e-06
500: 1.2204891059979977e-06
600: 9.866559495508433e-07
700: 7.977007067857415e-07
800: 6.449833432986498e-07
900: 5.215365405726201e-07
1000: 4.2173864614187064e-07


In [15]:
nn4.layers

[array([[-0.2948706]]), array([[-0.0051843]])]

In [16]:
nn4.biases

[array([[ 0.6778992]]), array([[ 0.00358136]])]

In [17]:
args = nn4.eval_sup(np.array([1.]).reshape(-1, 1), 
                    np.array([0.]).reshape(-1, 1))
args

(1.2730137277563454e-06,
 array([[ 1.]]),
 array([[ 0.]]),
 [array([[ 0.3830286]]), array([[ 0.00159563]])])

# Try a harder 2 layers with more neurons

In [18]:
np.random.seed(6)
nn4 = NeuralNet.NeuralNet(6, [4, 2], ["linear"]*2)

In [19]:
nn4.layers

[array([[-0.31178367,  0.72900392,  0.21782079, -0.8990918 , -2.48678065,
          0.91325152],
        [ 1.12706373, -1.51409323,  1.63929108, -0.4298936 ,  2.63128056,
          0.60182225],
        [-0.33588161,  1.23773784,  0.11112817,  0.12915125,  0.07612761,
         -0.15512816],
        [ 0.63422534,  0.810655  ,  0.35480861,  1.81259031, -1.3564758 ,
         -0.46363197]]),
 array([[ 0.82465384, -1.17643148,  1.56448966,  0.71270509],
        [-0.1810066 ,  0.53419953, -0.58661296, -1.48185327]])]

In [20]:
nn4.biases

[array([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.]]), array([[ 1.],
        [ 1.]])]

In [21]:
np.random.seed(111)
training_data = np.random.random((6, 256)) * 2 - 1
training_out = np.zeros((2, 256))

In [22]:
for i in range(1001):
    e = nn4.train_step(training_data, training_out, learning_rate=5e-2)
    
    if i % 100 == 0:
        print(f"{i}: {e}")

0: 20.342455144499578
100: 0.03467858244676142
200: 0.010155116769111567
300: 0.0038015862216867
400: 0.001533001200244172
500: 0.000635982198176282
600: 0.0002679415871275361
700: 0.00011422778763565493
800: 4.921730472348245e-05
900: 2.1418916520352715e-05
1000: 9.410448604289732e-06


In [23]:
nn4.layers

[array([[-0.40196803,  0.67460624,  0.11487169, -0.97074585, -2.29344254,
          0.8544733 ],
        [ 0.8336711 , -1.21636617,  1.34697806, -0.39944512,  2.49064593,
          0.5137335 ],
        [-0.01752111, -0.06301542,  0.02263606, -0.12186267,  0.1716696 ,
          0.03653912],
        [ 0.38534157,  0.43826566,  0.05299728,  1.39623266, -0.97372891,
         -0.44056583]]),
 array([[ 0.00144147, -0.00641608,  0.22922341,  0.01826167],
        [-0.00663143,  0.00586905, -0.38552533, -0.03706916]])]

In [24]:
nn4.biases

[array([[ 0.99592561],
        [ 1.48084901],
        [ 0.39114222],
        [ 1.10046932]]), array([[-0.10095678],
        [ 0.18970508]])]

# Try sigmoidal now

In [28]:
np.random.seed(24)
nn4 = NeuralNet.NeuralNet(6, [4, 2], ["sigmoid"]*2)

In [29]:
nn4.layers

[array([[ 1.32921217, -0.77003345, -0.31628036, -0.99081039, -1.07081626,
         -1.43871328],
        [ 0.56441685,  0.29572189, -1.62640423,  0.2195652 ,  0.6788048 ,
          1.88927273],
        [ 0.9615384 ,  0.1040112 , -0.48116532,  0.85022853,  1.45342467,
          1.05773744],
        [ 0.16556161,  0.51501838, -1.33693569,  0.56286114,  1.39285483,
         -0.06332798]]),
 array([[ 0.12166836,  1.20760254, -0.00204021,  1.62779574],
        [ 0.35449279,  1.03752763, -0.38568351,  0.519818  ]])]

In [30]:
nn4.biases

[array([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.]]), array([[ 1.],
        [ 1.]])]

In [31]:
np.random.seed(111)
training_data = np.random.random((6, 256)) * 2 - 1
training_out = np.zeros((2, 256))

In [37]:
for i in range(1001):
    e = nn4.train_step(training_data, training_out, learning_rate=2e-1)
    
    if i % 100 == 0:
        print(f"{i}: {e}")

0: 0.002416971242499569
100: 0.0019472568433159725
200: 0.0016274152476027923
300: 0.0013960028713456906
400: 0.0012210261442867525
500: 0.0010842159944214615
600: 0.0009743949958900937
700: 0.0008843474511969321
800: 0.000809210562645279
900: 0.000745589663841994
1000: 0.00069104421915915


In [33]:
nn4.layers

[array([[ 1.28728949, -0.76309155, -0.31789409, -0.97596442, -1.05241692,
         -1.40218155],
        [ 0.57976972,  0.32318842, -1.66216117,  0.22654504,  0.67964707,
          1.91029078],
        [ 0.88069813,  0.08791851, -0.47021528,  0.82081338,  1.38654038,
          1.04340882],
        [ 0.17260003,  0.54488212, -1.37662218,  0.57605731,  1.40651021,
         -0.08183874]]),
 array([[-1.10054868, -0.04200364, -1.39591382,  0.37453914],
        [-0.70320831, -0.00665001, -1.52044613, -0.51882068]])]

In [34]:
nn4.biases

[array([[ 1.20357509],
        [ 0.68970811],
        [ 1.44254748],
        [ 0.65698829]]), array([[-0.91286225],
        [-0.6163662 ]])]

In [38]:
args = nn4.eval_sup(np.array([1.]*6).reshape(-1, 1), 
                    np.array([0., 0]).reshape(-1, 1))
args

(0.00083986888805679511, array([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.]]), array([[ 0.],
        [ 0.]]), [array([[ 0.13257235],
         [ 0.94049122],
         [ 0.99485283],
         [ 0.87117409]]), array([[ 0.03424409],
         [ 0.02251845]])])

# Try recognizing handwritten digits

In [51]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original', data_home='./data/')

HTTPError: HTTP Error 500: Internal Server Error

In [52]:
iris = fetch_mldata('iris', data_home='./data/')

In [53]:
iris

{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: iris',
 'data': array([[ -5.55556000e-01,   2.50000000e-01,  -8.64407000e-01,
          -9.16667000e-01],
        [ -6.66667000e-01,  -1.66667000e-01,  -8.64407000e-01,
          -9.16667000e-01],
        [ -7.77778000e-01,   0.00000000e+00,  -8.98305000e-01,
          -9.16667000e-01],
        [ -8.33333000e-01,  -8.33334000e-02,  -8.30508000e-01,
          -9.16667000e-01],
        [ -6.11111000e-01,   3.33333000e-01,  -8.64407000e-01,
          -9.16667000e-01],
        [ -3.88889000e-01,   5.83333000e-01,  -7.62712000e-01,
          -7.50000000e-01],
        [ -8.33333000e-01,   1.66667000e-01,  -8.64407000e-01,
          -8.33333000e-01],
        [ -6.11111000e-01,   1.66667000e-01,  -8.30508000e-01,
          -9.16667000e-01],
        [ -9.44444000e-01,  -2.50000000e-01,  -8.64407000e-01,
          -9.16667000e-01],
        [ -6.66667000e-01,  -8.33334000e-02,  -8.30508000e-01,
          -1.00000000e+00],
        [ -